//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlubPilkarski.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZawodnikMecz
    {
        public int IdZM { get; set; }
        public int IdM { get; set; }
        public int IdZ { get; set; }
        public string Pozycja { get; set; }
        public int MinutyOd { get; set; }
        public int MinutyDo { get; set; }
        public int Bramki { get; set; }
        public int Asysty { get; set; }
        public int UtworzoneSzanse { get; set; }
        public int StrzalyCelne { get; set; }
        public int StrzalyNiecelne { get; set; }
        public int StrzalyZablokowane { get; set; }
        public int SlupkiPoprzeczki { get; set; }
        public int KartkiZolte { get; set; }
        public int KartkiCzerwone { get; set; }
        public int PodaniaUdanePolowaWlasna { get; set; }
        public int PodaniaUdanePolowaPrzeciwnika { get; set; }
        public int PodaniaNieudanePolowaWlasna { get; set; }
        public int PodaniaNieudanePolowaPrzeciwnika { get; set; }
        public int Dosrodkowania { get; set; }
        public int DlugiePodaniaUdane { get; set; }
        public int DlugiePodaniaNieudane { get; set; }
        public int KluczowePodania { get; set; }
        public int Kontakty { get; set; }
        public int RzutyRozne { get; set; }
        public int Wyrzuty { get; set; }
        public int PojedynkiWygrane { get; set; }
        public int PojedynkiPrzegrane { get; set; }
        public int Wybicia { get; set; }
        public int DryblingiUdane { get; set; }
        public int Straty { get; set; }
        public int Faulowany { get; set; }
        public int Faule { get; set; }
        public int OdbioryUdane { get; set; }
        public int OdbioryNieudane { get; set; }
        public int GlowkiWygrane { get; set; }
        public int GlowkiPrzegrane { get; set; }
        public int Przejecia { get; set; }
        public int Spalone { get; set; }
        public int OdzyskanePilki { get; set; }
        public int ObronaWyskok { get; set; }
        public int ObronaPoleKarne { get; set; }
        public int ObronaWyjscie { get; set; }
        public int Piastkowania { get; set; }
        public int ObronaWysokiejPilki { get; set; }
        public int Forma { get; set; }
    
        public virtual Mecz Mecz { get; set; }
        public virtual Zawodnik Zawodnik { get; set; }
    }
}
